const BYTES_PER_MEGABYTE = 1024 * 1024;

export const IMAGE_UPLOAD_MAX_MEGABYTES = 8;
export const IMAGE_UPLOAD_MAX_BYTES = IMAGE_UPLOAD_MAX_MEGABYTES * BYTES_PER_MEGABYTE;

export const CHAT_IMPORT_MAX_MEGABYTES = 10;
export const CHAT_IMPORT_MAX_BYTES = CHAT_IMPORT_MAX_MEGABYTES * BYTES_PER_MEGABYTE;
